# Generated by Django 6.0.5 on 2026-05-20 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер'), ('admin', 'Управляющий'), ('support', 'Сотрудник Call-центра')], default='manager', max_length=50, verbose_name='Роль')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Оклад')),
                ('bonus_percent', models.FloatField(default=0.0, verbose_name='Процент бонуса (%)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
