# Generated by Django 6.0.5 on 2026-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон менеджера'),
        ),
    ]
