# Generated by Django 6.0.5 on 2026-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_manager_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер WhatsApp'),
        ),
    ]
