# Generated by Django 6.0.5 on 2026-05-20 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_managerprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма выплаты')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выплаты')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='shop.managerprofile', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Логи выплат',
                'ordering': ['-date'],
            },
        ),
    ]
